export const demoCopy = {
  'zh-CN': {
    tabs: { build: '构建', style: '样式', registry: '组件', sqlite: '数据', migration: '迁移' },
    playground: '工具示例',
    source: '代码',
    result: '浏览器预览',
    copy: '复制代码',
    copied: '已复制',
    copyFailed: '复制失败，代码已选中，请手动复制。',
    official: '官方文档',
    color: '颜色',
    colors: ['松绿', '钴蓝', '玫红'],
    radius: '圆角',
    radii: ['直角', '适中', '柔和'],
    compact: '紧凑',
    button: '开始构建',
    saved: '准备好了',
    styleNote: 'Tailwind CSS · Web',
    target: '目标平台',
    targets: ['微信', '支付宝', '抖音'],
    output: '输出目录示例',
    buildNote: '多平台模板 · experimental',
    components: '组件',
    registryNote: '交互示意 · 规划中',
    registryTitle: '你的下一个项目',
    input: '项目名称',
    inputValue: 'my-mini-app',
    selected: '已选择',
    registryAction: '确认项目',
    registryDone: '已确认',
  },
  'en': {
    tabs: { build: 'Build', style: 'Style', registry: 'Compose', sqlite: 'Data', migration: 'Migrate' },
    playground: 'Tool examples',
    source: 'Code',
    result: 'Browser preview',
    copy: 'Copy code',
    copied: 'Copied',
    copyFailed: 'Copy failed. The code is selected for manual copying.',
    official: 'Documentation',
    color: 'Color',
    colors: ['Green', 'Blue', 'Rose'],
    radius: 'Corners',
    radii: ['Square', 'Medium', 'Soft'],
    compact: 'Compact',
    button: 'Start building',
    saved: 'Ready to build',
    styleNote: 'Tailwind CSS · Web',
    target: 'Platform',
    targets: ['WeChat', 'Alipay', 'Douyin'],
    output: 'Example output',
    buildNote: 'Multi-platform template · experimental',
    components: 'Components',
    registryNote: 'Interaction sketch · Planned',
    registryTitle: 'Your next project',
    input: 'Project name',
    inputValue: 'my-mini-app',
    selected: 'Selected',
    registryAction: 'Confirm project',
    registryDone: 'Confirmed',
  },
} as const
